{"name": "test_second", "status": "failed", "statusDetails": {"message": "AssertionError: assert 77 == 88", "trace": "def test_second():\n        a = 33\n        b = 44\n        result = a + b\n>       assert result == 88\nE       assert 77 == 88\n\ntest_pythonMarkers.py:18: AssertionError"}, "start": 1647109467392, "stop": 1647109467393, "uuid": "a8625d47-e737-44bd-a1fb-a3bfbd8bb824", "historyId": "fb2f67dc1731a8e2dfa248b7f5501ed8", "testCaseId": "855c6fc93cd84522af609dba448b1ef4", "fullName": "test_pythonMarkers#test_second", "labels": [{"name": "suite", "value": "test_pythonMarkers"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "13100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pythonMarkers"}]}